version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Flask API port
    environment:
      - FLASK_ENV=production
    restart: always  # Ensure the backend restarts if it crashes

  frontend:
    build:
      context: ./frontend
    command: npm run build  # Build the React app
    ports:
      - "3000:3000"  # Serve the frontend React app on port 80 (if needed)
    stdin_open: true
    tty: true
    restart: always
