version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Flask API port
    environment:
      - FLASK_ENV=production
    restart: always  # Ensure the backend restarts if it crashes

  frontend:
    image: nginx:latest  # Use Nginx to serve the static build files
    ports:
      - "80:80"  # Serve on port 80 for public access
    volumes:
      - ./frontend/build:/usr/share/nginx/html  # Serve the static build folder
    restart: always
