version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - nginx

  frontend:
    build:
      context: ./frontend
    command: npm run build  # Build React app
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html  # Serve built frontend
    depends_on:
      - backend
      - frontend
