version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Flask API port (external 8000 to internal 8000)
    environment:
      - FLASK_ENV=production
    restart: always  # Ensure the backend restarts if it crashes

  frontend:
    build:
      context: ./frontend
    command: npm run build  # Build the React app
    ports:
      - "80:80"  # Serve the frontend React app on port 80 (internally and externally)
    stdin_open: true
    tty: true
    restart: always  # Restart if the container crashes
