version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: always  # Ensure the backend restarts if it crashes

  frontend:
    build:
      context: ./frontend
    command: npm run build  # Build the React app
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx config for serving HTTPS and routing
      - ./frontend/build:/usr/share/nginx/html  # Serve the React app's build folder as static files
    restart: always
